Controllers/AuthController.cs
using Counselors_Connect.Data;
using Counselors_Connect.Models;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.CookiePolicy;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using NuGet.Protocol;
namespace Counselors_Connect.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class AuthController : ControllerBase
    {

        private readonly AppDbContext _context;

        public AuthController(AppDbContext context)
        {
            _context = context;
        }
        [HttpGet("username")]
        public ActionResult<string> GetUsername()
        {
            var userName = User.FindFirst(ClaimTypes.Name)?.Value.ToJson();
            if (userName == null)
            {
                return Unauthorized();
            }
            return Ok(userName);
        }

        [AllowAnonymous]
        [HttpPost("login")]
        public async Task<IActionResult> Login([FromBody] LoginDTO loginDTO)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var user = await _context.Counselors
                .FirstOrDefaultAsync(u => u.Username == loginDTO.Username);

            if (user != null && user.Password == loginDTO.Password)
            {
                var claims = new List<Claim>
        {
            new Claim(ClaimTypes.Name, user.Username),
        };

                var claimsIdentity = new ClaimsIdentity(
                    claims, CookieAuthenticationDefaults.AuthenticationScheme);

                var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);


                await HttpContext.SignInAsync(
                    CookieAuthenticationDefaults.AuthenticationScheme,
                    claimsPrincipal,
                    new AuthenticationProperties
                    {
                        IsPersistent = loginDTO.RememberMe, 
                        ExpiresUtc = DateTimeOffset.UtcNow.AddDays(1) 
                    });

                return Ok(new { Message = "Login successful" });
            }
            else
            {
                return Unauthorized(new {Message = "Invalid username or password"});
            }
        }

        [HttpPost("logout")]
        public async Task<IActionResult> Logout()
        { 
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return RedirectToAction("Index", "Login"); 
        }
    }
}

Controllers/CreateController.cs
using Microsoft.AspNetCore.Mvc;

namespace Counselors_Connect.Controllers
{
    public class CreateController : Controller
    {
        public IActionResult CreateAVisit()
        {
            return View();
        }

        public IActionResult CreateAStudent()
        {
            return View();
        }

        public IActionResult CreateATopic()
        {
            return View();
        }
    }
}

Controllers/StudentViewController.cs
using Microsoft.AspNetCore.Mvc;

namespace Counselors_Connect.Controllers
{
    public class StudentViewController : Controller
    {
        public IActionResult StudentView()
        {
            return View();
        }
    }
}

Controllers/TopicViewController.cs
using Microsoft.AspNetCore.Mvc;

namespace Counselors_Connect.Controllers
{
    public class TopicViewController : Controller
    {
        public IActionResult TopicView()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
@using System.Security.Claims


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Counselors Connect</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/compiledscss/main.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
</head>

<body>
            @if (ViewData["HideNavBar"] == null || !(bool)ViewData["HideNavBar"])
        {
            <div id="all-content" class="row g-0">
        <div class="col-xxl-2 p-0">
            <div id="sidebar-menu" class="d-sm-none d-xxl-block bg-light sidebar collapse" aria-label="Side Navigation">
                <div class="position-sticky pt-xl-3">
                    <ul class="nav flex-column">
                            <li class="nav-item">
                                <a class="btn nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                                    <span>
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="white" class="bi bi-house" viewBox="0 0 16 16">
                                            <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293zM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5z" />
                                        </svg>
                                    </span>
                                    Home
                                </a>
                            </li>
                        <li class="nav-item">
                            <a class="btn nav-link" asp-area="" asp-controller="StudentView" asp-action="StudentView">
                                <span data-feather="users"></span>
                                Student View
                            </a>
                        </li>                       
                            <li class="nav-item">
                                <a class="btn nav-link" asp-area="" asp-controller="TopicView" asp-action="TopicView">
                                    <span data-feather="book"></span>
                                    Topic View
                                </a>
                            </li>
                            <li class="nav-item m-2">
                                <div id="nav-edit-heading" class="ps-0">
                                    <p class="fs-4 m-0 ms-5">
                                        Create
                                    </p>
                                </div>
                                <div id="nav-edit-body" class="py-2">
                                    <a class="btn nav-link" asp-area="" asp-controller="Create" asp-action="CreateAVisit">
                                        <span data-feather="plus-circle"></span>
                                        Visit
                                    </a>
                                    <a class="btn nav-link" asp-area="" asp-controller="Create" asp-action="CreateATopic">
                                        <span data-feather="plus-circle"></span>
                                        Topic
                                    </a>
                                    <a class="btn nav-link" asp-area="" asp-controller="Create" asp-action="CreateAStudent">
                                        <span data-feather="plus-circle"></span>
                                        Student
                                    </a>
                                </div>
                            </li>

                       
                    </ul>
                </div>
                    <div id="log-out-container">
                        <a id="log-out-btn" class="btn" href="javascript:void(0);" onclick="document.getElementById('logoutForm').submit();">
                            <span data-feather="log-out"></span>
                            Log Out
                        </a>
                    </div>
                
            </div>
            <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasnav" aria-labelledby="offcanvasLabel" style="visibility: hidden;background-color: rgb(41, 67, 22) !important;" aria-modal="true" role="dialog">
                <div class="offcanvas-header pt-2 nav">
                    <a id="close-offcanvas" class="btn me-2" href="#" type="button" data-bs-dismiss="offcanvas" aria-label="Close">
                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="white" class="bi bi-x-lg" viewBox="0 0 16 16">
                            <path d="M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8z" />
                        </svg>
                    </a>
                </div>
                <div class="offcanvas-body">
                    <div class="position-sticky">
                        <ul  class="nav flex-column">
                                <li class="nav-item">
                                    <a class="btn nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                                        <span>
                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="white" class="bi bi-house" viewBox="0 0 16 16">
                                                <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293zM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5z" />
                                            </svg>
                                        </span>
                                        Home
                                    </a>
                                </li>
                            <li class="nav-item">
                                <a class="btn nav-link" asp-area="" asp-controller="StudentView" asp-action="StudentView">
                                    <span data-feather="users"></span>
                                    Student View
                                </a>
                            </li>
                                <li class="nav-item">
                                    <a class="btn nav-link" asp-area="" asp-controller="TopicView" asp-action="TopicView">
                                        <span data-feather="book"></span>
                                        Topic View
                                    </a>
                                </li>
                            <li class="nav-item m-2">
                                <div id="nav-edit-heading" class="ps-0">
                                    <p class="fs-4 m-0 ms-5">
                                        Create
                                    </p>
                                </div>
                                <div id="nav-edit-body" class="py-2">
                                        <a class="btn nav-link" asp-area="" asp-controller="Create" asp-action="CreateAVisit">
                                            <span data-feather="plus-circle"></span>
                                        Visit
                                    </a>
                                        <a class="btn nav-link" asp-area="" asp-controller="Create" asp-action="CreateATopic">
                                            <span data-feather="plus-circle"></span>
                                        Topic
                                    </a>
                                        <a class="btn nav-link" asp-area="" asp-controller="Create" asp-action="CreateAStudent">
                                            <span data-feather="plus-circle"></span>
                                        Student
                                    </a>
                                </div>
                            </li>
                          
                            
                           


                        </ul>
                    </div>
                        <div id="log-out-container">
                            <a id="log-out-btn" class="btn" href="javascript:void(0);" onclick="document.getElementById('logoutForm').submit();">
                                <span data-feather="log-out"></span>
                                Log Out
                            </a>
                        </div>
                </div>
            </div>
        </div>   

        <div class="col-12 col-xxl-10">
            <div class="row g-0 m-0">
                <nav class="navbar shadow" aria-label="Top Navigation" id="top-navigation">
                    <button class="btn navbar-toggler ms-2 d-xxl-none d-sm-block d-md-block d-xl-block" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasnav" aria-controls="offcanvasnav" aria-label="Toggle navigation">
                        <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5" />
                        </svg>
                    </button>
                    <p class="page-title fs-2 ps-xxl-5">@ViewData["Title"]</p>
                    <button class="navbar-toggler collapsed me-xxl-5" type="button" aria-label="Displays teacher that is loged in.">
                        @User.FindFirst(ClaimTypes.Name)?.Value
                    </button>
                </nav>

                <main id="main-content">
                    @RenderBody()
                </main>
            </div>
        </div>

    </div>
    }
    else
    {
        <main class="container-fluid custom-container-fluid">
            @RenderBody()
        </main>
    }

    <form id="logoutForm" asp-controller="Auth" asp-action="Logout" method="post" style="display: none;">
    </form>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://unpkg.com/feather-icons"></script>
    <script src="https://cdn.jsdelivr.net/npm/fuse.js/dist/fuse.js"></script>
    <script src="https://unpkg.com/react@18/umd/react.development.js"></script>
    <script src="https://unpkg.com/react-dom@18/umd/react-dom.development.js"></script>
    <script>
        feather.replace()
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>